apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: hello-worldn-0b512e8b-25ec-4dd0-a940-a0f21c6e61e0
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
