apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: my-storage-bucket-15067212-9486-43fd-b3d1-2d8eb5babcf4
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
