apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: harec-1fb0cf44-250d-4fb3-afa1-a927df3f2d95
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
