apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: hello-world-88af3800-8fb7-4e9a-910e-3ce422cd895b
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
