apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: my-storage-bucket-a65e1c84-ea20-46bb-ab09-fe8d4c06875d
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
