apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: jajaja-b14c894e-9bd2-40ec-9754-7c1841338ad9
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
