apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: hello-world-bd154849-cd6e-429d-98e5-ebbb19974218
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
