apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: sample-crossplane-bucket-
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default